#*****************************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# vivado_project.tcl: Tcl script for re-creating project 'vivado_project'
#
# Generated by Vivado on Mon May 25 00:00:00 +0300 2020
# IP Build 2548770 on Fri May 24 18:01:18 MDT 2019
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (vivado_project.tcl) that was generated.
#
#*****************************************************************************************

set target_board "digilent_nexys_a7_100t"
#set target_board "digilent_arty_a7_35t"

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
if {$target_board == "digilent_arty_a7_35t"} {
  set _xil_proj_name_ "pulpino_arty_a7_35t"
}

if {$target_board == "digilent_nexys_a7_100t"} {
  set _xil_proj_name_ "pulpino_nexys_a7_100t"
}


# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "vivado_project.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/vivado_project"]"

# Create project
if {$target_board == "digilent_arty_a7_35t"} {
  create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7a35ticsg324-1L
}

if {$target_board == "digilent_nexys_a7_100t"} {
  create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7a100tcsg324-1
}

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
#set obj [current_project]
#set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
#set_property -name "dsa.accelerator_binary_content" -value "bitstream" -objects $obj
#set_property -name "dsa.accelerator_binary_format" -value "xclbin2" -objects $obj
#set_property -name "dsa.description" -value "Vivado generated DSA" -objects $obj
#set_property -name "dsa.dr_bd_base_address" -value "0" -objects $obj
#set_property -name "dsa.emu_dir" -value "emu" -objects $obj
#set_property -name "dsa.flash_interface_type" -value "bpix16" -objects $obj
#set_property -name "dsa.flash_offset_address" -value "0" -objects $obj
#set_property -name "dsa.flash_size" -value "1024" -objects $obj
#set_property -name "dsa.host_architecture" -value "x86_64" -objects $obj
#set_property -name "dsa.host_interface" -value "pcie" -objects $obj
#set_property -name "dsa.num_compute_units" -value "60" -objects $obj
#set_property -name "dsa.platform_state" -value "pre_synth" -objects $obj
#set_property -name "dsa.vendor" -value "xilinx" -objects $obj
#set_property -name "dsa.version" -value "0.0" -objects $obj
#set_property -name "enable_vhdl_2008" -value "1" -objects $obj
#set_property -name "ip_cache_permissions" -value "read write" -objects $obj
#set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
#set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
#set_property -name "part" -value "xc7a35ticsg324-1L" -objects $obj
#set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
#set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
#set_property -name "simulator_language" -value "Mixed" -objects $obj
#set_property -name "xpm_libraries" -value "XPM_CDC XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/rtl/config.sv"] \
 [file normalize "${origin_dir}/submodules/adv_dbg_if/rtl/adbg_crc32.v"] \
 [file normalize "${origin_dir}/submodules/adv_dbg_if/rtl/adbg_tap_defines.v"] \
 [file normalize "${origin_dir}/submodules/adv_dbg_if/rtl/adbg_tap_top.v"] \
 [file normalize "${origin_dir}/submodules/axi/axi_slice_dc/dc_data_buffer.v"] \
 [file normalize "${origin_dir}/submodules/axi/axi_slice_dc/dc_full_detector.v"] \
 [file normalize "${origin_dir}/submodules/axi/axi_slice_dc/dc_synchronizer.v"] \
 [file normalize "${origin_dir}/submodules/axi/axi_slice_dc/dc_token_ring.v"] \
 [file normalize "${origin_dir}/submodules/axi/axi_slice_dc/dc_token_ring_fifo_din.v"] \
 [file normalize "${origin_dir}/submodules/axi/axi_slice_dc/dc_token_ring_fifo_dout.v"] \
 [file normalize "${origin_dir}/rtl/includes/axi_bus.sv"] \
 [file normalize "${origin_dir}/submodules/adv_dbg_if/rtl/adbg_axi_biu.sv"] \
 [file normalize "${origin_dir}/submodules/adv_dbg_if/rtl/adbg_defines.v"] \
 [file normalize "${origin_dir}/submodules/adv_dbg_if/rtl/adbg_axi_defines.v"] \
 [file normalize "${origin_dir}/submodules/adv_dbg_if/rtl/adbg_axi_module.sv"] \
 [file normalize "${origin_dir}/submodules/adv_dbg_if/rtl/adbg_or1k_biu.sv"] \
 [file normalize "${origin_dir}/submodules/adv_dbg_if/rtl/adbg_or1k_defines.v"] \
 [file normalize "${origin_dir}/submodules/adv_dbg_if/rtl/adbg_or1k_module.sv"] \
 [file normalize "${origin_dir}/submodules/adv_dbg_if/rtl/adbg_or1k_status_reg.sv"] \
 [file normalize "${origin_dir}/submodules/adv_dbg_if/rtl/adbg_top.sv"] \
 [file normalize "${origin_dir}/submodules/adv_dbg_if/rtl/adv_dbg_if.sv"] \
 [file normalize "${origin_dir}/submodules/apb/apb2per/apb2per.sv"] \
 [file normalize "${origin_dir}/rtl/includes/apb_bus.sv"] \
 [file normalize "${origin_dir}/submodules/apb/apb_event_unit/include/defines_event_unit.sv"] \
 [file normalize "${origin_dir}/submodules/apb/apb_event_unit/apb_event_unit.sv"] \
 [file normalize "${origin_dir}/submodules/apb/apb_fll_if/apb_fll_if.sv"] \
 [file normalize "${origin_dir}/submodules/apb/apb_gpio/apb_gpio.sv"] \
 [file normalize "${origin_dir}/submodules/apb/apb_i2c/apb_i2c.sv"] \
 [file normalize "${origin_dir}/submodules/apb/apb_node/apb_node.sv"] \
 [file normalize "${origin_dir}/submodules/apb/apb_node/apb_node_wrap.sv"] \
 [file normalize "${origin_dir}/submodules/apb/apb_pulpino/apb_pulpino.sv"] \
 [file normalize "${origin_dir}/submodules/apb/apb_spi_master/apb_spi_master.sv"] \
 [file normalize "${origin_dir}/submodules/apb/apb_timer/apb_timer.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi2apb/axi2apb.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi2apb/axi2apb32.sv"] \
 [file normalize "${origin_dir}/rtl/axi2apb_wrap.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_node/axi_AR_allocator.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_node/axi_AW_allocator.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_node/axi_ArbitrationTree.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_node/axi_BR_allocator.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_node/axi_BW_allocator.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_node/axi_DW_allocator.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_node/axi_FanInPrimitive_Req.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_node/axi_RR_Flag_Req.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_node/axi_address_decoder_AR.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_node/axi_address_decoder_AW.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_node/axi_address_decoder_BR.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_node/axi_address_decoder_BW.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_node/axi_address_decoder_DW.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_slice/axi_ar_buffer.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_slice/axi_aw_buffer.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_slice/axi_b_buffer.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_mem_if_DP/axi_mem_if_SP.sv"] \
 [file normalize "${origin_dir}/rtl/axi_mem_if_SP_wrap.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_node/axi_multiplexer.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_node/axi_node.sv"] \
 [file normalize "${origin_dir}/rtl/axi_node_intf_wrap.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_slice/axi_r_buffer.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_mem_if_DP/axi_read_only_ctrl.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_node/axi_request_block.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_node/axi_response_block.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_slice/axi_slice.sv"] \
 [file normalize "${origin_dir}/rtl/axi_slice_wrap.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_spi_slave/axi_spi_slave.sv"] \
 [file normalize "${origin_dir}/rtl/axi_spi_slave_wrap.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_slice/axi_w_buffer.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_mem_if_DP/axi_write_only_ctrl.sv"] \
 [file normalize "${origin_dir}/rtl/boot_code.sv"] \
 [file normalize "${origin_dir}/rtl/boot_rom_wrap.sv"] \
 [file normalize "${origin_dir}/rtl/clk_rst_gen.sv"] \
 [file normalize "${origin_dir}/rtl/components/cluster_clock_gating.sv"] \
 [file normalize "${origin_dir}/rtl/components/cluster_clock_inverter.sv"] \
 [file normalize "${origin_dir}/rtl/components/cluster_clock_mux2.sv"] \
 [file normalize "${origin_dir}/submodules/axi/core2axi/core2axi.sv"] \
 [file normalize "${origin_dir}/rtl/core2axi_wrap.sv"] \
 [file normalize "${origin_dir}/rtl/core_region.sv"] \
 [file normalize "${origin_dir}/rtl/includes/debug_bus.sv"] \
 [file normalize "${origin_dir}/rtl/components/generic_fifo.sv"] \
 [file normalize "${origin_dir}/submodules/apb/apb_event_unit/generic_service_unit.sv"] \
 [file normalize "${origin_dir}/submodules/apb/apb_i2c/i2c_master_bit_ctrl.sv"] \
 [file normalize "${origin_dir}/submodules/apb/apb_i2c/i2c_master_byte_ctrl.sv"] \
 [file normalize "${origin_dir}/rtl/instr_ram_wrap.sv"] \
 [file normalize "${origin_dir}/rtl/periph_bus_wrap.sv"] \
 [file normalize "${origin_dir}/rtl/peripherals.sv"] \
 [file normalize "${origin_dir}/rtl/components/pulp_clock_inverter.sv"] \
 [file normalize "${origin_dir}/rtl/components/pulp_clock_mux2.sv"] \
 [file normalize "${origin_dir}/rtl/pulpino_top.sv"] \
 [file normalize "${origin_dir}/rtl/ram_mux.sv"] \
 [file normalize "${origin_dir}/rtl/components/rstgen.sv"] \
 [file normalize "${origin_dir}/submodules/apb/apb_event_unit/sleep_unit.sv"] \
 [file normalize "${origin_dir}/rtl/sp_ram_wrap.sv"] \
 [file normalize "${origin_dir}/submodules/apb/apb_spi_master/spi_master_apb_if.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_spi_master/spi_master_clkgen.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_spi_master/spi_master_controller.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_spi_master/spi_master_fifo.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_spi_master/spi_master_rx.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_spi_master/spi_master_tx.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_spi_slave/spi_slave_axi_plug.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_spi_slave/spi_slave_cmd_parser.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_spi_slave/spi_slave_controller.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_spi_slave/spi_slave_dc_fifo.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_spi_slave/spi_slave_regs.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_spi_slave/spi_slave_rx.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_spi_slave/spi_slave_syncro.sv"] \
 [file normalize "${origin_dir}/submodules/axi/axi_spi_slave/spi_slave_tx.sv"] \
 [file normalize "${origin_dir}/submodules/apb/apb_timer/timer.sv"] \
 [file normalize "${origin_dir}/submodules/zero-riscy/include/zeroriscy_defines.sv"] \
 [file normalize "${origin_dir}/submodules/zero-riscy/include/zeroriscy_config.sv"] \
 [file normalize "${origin_dir}/submodules/zero-riscy/zeroriscy_alu.sv"] \
 [file normalize "${origin_dir}/submodules/zero-riscy/zeroriscy_compressed_decoder.sv"] \
 [file normalize "${origin_dir}/submodules/zero-riscy/zeroriscy_controller.sv"] \
 [file normalize "${origin_dir}/submodules/zero-riscy/zeroriscy_core.sv"] \
 [file normalize "${origin_dir}/submodules/zero-riscy/zeroriscy_cs_registers.sv"] \
 [file normalize "${origin_dir}/submodules/zero-riscy/zeroriscy_debug_unit.sv"] \
 [file normalize "${origin_dir}/submodules/zero-riscy/zeroriscy_decoder.sv"] \
 [file normalize "${origin_dir}/submodules/zero-riscy/zeroriscy_ex_block.sv"] \
 [file normalize "${origin_dir}/submodules/zero-riscy/zeroriscy_fetch_fifo.sv"] \
 [file normalize "${origin_dir}/submodules/zero-riscy/zeroriscy_id_stage.sv"] \
 [file normalize "${origin_dir}/submodules/zero-riscy/zeroriscy_if_stage.sv"] \
 [file normalize "${origin_dir}/submodules/zero-riscy/zeroriscy_int_controller.sv"] \
 [file normalize "${origin_dir}/submodules/zero-riscy/zeroriscy_load_store_unit.sv"] \
 [file normalize "${origin_dir}/submodules/zero-riscy/zeroriscy_multdiv_fast.sv"] \
 [file normalize "${origin_dir}/submodules/zero-riscy/zeroriscy_multdiv_slow.sv"] \
 [file normalize "${origin_dir}/submodules/zero-riscy/zeroriscy_prefetch_buffer.sv"] \
 [file normalize "${origin_dir}/submodules/zero-riscy/zeroriscy_register_file_ff.sv"] \
 [file normalize "${origin_dir}/submodules/apb/apb_uart/apb_uart.vhd"] \
 [file normalize "${origin_dir}/submodules/apb/apb_uart/slib_clock_div.vhd"] \
 [file normalize "${origin_dir}/submodules/apb/apb_uart/slib_counter.vhd"] \
 [file normalize "${origin_dir}/submodules/apb/apb_uart/slib_edge_detect.vhd"] \
 [file normalize "${origin_dir}/submodules/apb/apb_uart/slib_fifo.vhd"] \
 [file normalize "${origin_dir}/submodules/apb/apb_uart/slib_input_filter.vhd"] \
 [file normalize "${origin_dir}/submodules/apb/apb_uart/slib_input_sync.vhd"] \
 [file normalize "${origin_dir}/submodules/apb/apb_uart/slib_mv_filter.vhd"] \
 [file normalize "${origin_dir}/submodules/apb/apb_uart/uart_baudgen.vhd"] \
 [file normalize "${origin_dir}/submodules/apb/apb_uart/uart_interrupt.vhd"] \
 [file normalize "${origin_dir}/submodules/apb/apb_uart/uart_receiver.vhd"] \
 [file normalize "${origin_dir}/submodules/apb/apb_uart/uart_transmitter.vhd"] \
 [file normalize "${origin_dir}/rtl/includes/apu_defines.sv"] \
 [file normalize "${origin_dir}/submodules/adv_dbg_if/rtl/adbg_lint_defines.v"] \
 [file normalize "${origin_dir}/submodules/riscv/include/apu_core_package.sv"] \
 [file normalize "${origin_dir}/submodules/riscv/riscv_L0_buffer.sv"] \
 [file normalize "${origin_dir}/submodules/riscv/include/riscv_defines.sv"] \
 [file normalize "${origin_dir}/submodules/riscv/riscv_alu.sv"] \
 [file normalize "${origin_dir}/submodules/riscv/riscv_alu_div.sv"] \
 [file normalize "${origin_dir}/submodules/riscv/include/apu_macros.sv"] \
 [file normalize "${origin_dir}/submodules/riscv/riscv_apu_disp.sv"] \
 [file normalize "${origin_dir}/submodules/riscv/riscv_compressed_decoder.sv"] \
 [file normalize "${origin_dir}/submodules/riscv/riscv_controller.sv"] \
 [file normalize "${origin_dir}/submodules/riscv/riscv_core.sv"] \
 [file normalize "${origin_dir}/submodules/riscv/riscv_cs_registers.sv"] \
 [file normalize "${origin_dir}/submodules/riscv/riscv_debug_unit.sv"] \
 [file normalize "${origin_dir}/submodules/riscv/riscv_decoder.sv"] \
 [file normalize "${origin_dir}/submodules/riscv/riscv_ex_stage.sv"] \
 [file normalize "${origin_dir}/submodules/riscv/riscv_fetch_fifo.sv"] \
 [file normalize "${origin_dir}/submodules/riscv/riscv_hwloop_controller.sv"] \
 [file normalize "${origin_dir}/submodules/riscv/riscv_hwloop_regs.sv"] \
 [file normalize "${origin_dir}/submodules/riscv/riscv_id_stage.sv"] \
 [file normalize "${origin_dir}/submodules/riscv/riscv_if_stage.sv"] \
 [file normalize "${origin_dir}/submodules/riscv/riscv_int_controller.sv"] \
 [file normalize "${origin_dir}/submodules/riscv/riscv_load_store_unit.sv"] \
 [file normalize "${origin_dir}/submodules/riscv/riscv_mult.sv"] \
 [file normalize "${origin_dir}/submodules/riscv/riscv_prefetch_L0_buffer.sv"] \
 [file normalize "${origin_dir}/submodules/riscv/riscv_prefetch_buffer.sv"] \
 [file normalize "${origin_dir}/submodules/riscv/riscv_register_file.sv"] \
 [file normalize "${origin_dir}/rtl/xilinx_spram.v"] \
 [file normalize "${origin_dir}/rtl/kuznechik_cipher.sv"] \
 [file normalize "${origin_dir}/rtl/kuznechik_cipher_apb_wrapper.sv"] \
 [file normalize "${origin_dir}/sw/test_sw_emb_text.dat"] \
 [file normalize "${origin_dir}/sw/test_sw_emb_data.dat"] \
 [file normalize "${origin_dir}/sw/boot_code.dat"] \
 [file normalize "${origin_dir}/rtl/look_up_tables/keys.mem"] \
 [file normalize "${origin_dir}/rtl/look_up_tables/S_box.mem"] \
 [file normalize "${origin_dir}/rtl/look_up_tables/S_box_inverted.mem"] \
 [file normalize "${origin_dir}/rtl/look_up_tables/L_muliplications/L_16.mem"] \
 [file normalize "${origin_dir}/rtl/look_up_tables/L_muliplications/L_32.mem"] \
 [file normalize "${origin_dir}/rtl/look_up_tables/L_muliplications/L_133.mem"] \
 [file normalize "${origin_dir}/rtl/look_up_tables/L_muliplications/L_148.mem"] \
 [file normalize "${origin_dir}/rtl/look_up_tables/L_muliplications/L_192.mem"] \
 [file normalize "${origin_dir}/rtl/look_up_tables/L_muliplications/L_194.mem"] \
 [file normalize "${origin_dir}/rtl/look_up_tables/L_muliplications/L_251.mem"] \
]


# [file normalize "${origin_dir}/submodules/riscv/riscv_tracer.sv"] \
# [file normalize "${origin_dir}/submodules/riscv/riscv_alu_basic.sv"] \
# [file normalize "${origin_dir}/rtl/pulpino_arty.sv"] \

add_files -norecurse -fileset $obj $files

if {$target_board == "digilent_arty_a7_35t"} {
  add_files -norecurse -fileset $obj "${origin_dir}/rtl/pulpino_arty_a7.sv"
}


if {$target_board == "digilent_nexys_a7_100t"} {
  add_files -norecurse -fileset $obj "${origin_dir}/rtl/pulpino_nexys_a7.sv"
}



# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/rtl/config.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj
set_property -name "is_global_include" -value "1" -objects $file_obj

set file "$origin_dir/rtl/includes/axi_bus.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "$origin_dir/submodules/adv_dbg_if/rtl/adbg_axi_biu.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/adv_dbg_if/rtl/adbg_axi_module.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/adv_dbg_if/rtl/adbg_or1k_biu.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/adv_dbg_if/rtl/adbg_or1k_module.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/adv_dbg_if/rtl/adbg_or1k_status_reg.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/adv_dbg_if/rtl/adbg_top.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/adv_dbg_if/rtl/adv_dbg_if.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/apb/apb2per/apb2per.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/includes/apb_bus.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/apb/apb_event_unit/include/defines_event_unit.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "$origin_dir/submodules/apb/apb_event_unit/apb_event_unit.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/apb/apb_fll_if/apb_fll_if.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/apb/apb_gpio/apb_gpio.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/apb/apb_i2c/apb_i2c.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/apb/apb_node/apb_node.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/apb/apb_node/apb_node_wrap.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/apb/apb_pulpino/apb_pulpino.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/apb/apb_spi_master/apb_spi_master.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/apb/apb_timer/apb_timer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi2apb/axi2apb.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi2apb/axi2apb32.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/axi2apb_wrap.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_node/axi_AR_allocator.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_node/axi_AW_allocator.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_node/axi_ArbitrationTree.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_node/axi_BR_allocator.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_node/axi_BW_allocator.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_node/axi_DW_allocator.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_node/axi_FanInPrimitive_Req.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_node/axi_RR_Flag_Req.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_node/axi_address_decoder_AR.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_node/axi_address_decoder_AW.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_node/axi_address_decoder_BR.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_node/axi_address_decoder_BW.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_node/axi_address_decoder_DW.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_slice/axi_ar_buffer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_slice/axi_aw_buffer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_slice/axi_b_buffer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_mem_if_DP/axi_mem_if_SP.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/axi_mem_if_SP_wrap.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_node/axi_multiplexer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_node/axi_node.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/axi_node_intf_wrap.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_slice/axi_r_buffer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_mem_if_DP/axi_read_only_ctrl.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_node/axi_request_block.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_node/axi_response_block.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_slice/axi_slice.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/axi_slice_wrap.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_spi_slave/axi_spi_slave.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/axi_spi_slave_wrap.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_slice/axi_w_buffer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_mem_if_DP/axi_write_only_ctrl.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/boot_code.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/boot_rom_wrap.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/clk_rst_gen.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/components/cluster_clock_gating.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/components/cluster_clock_inverter.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/components/cluster_clock_mux2.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/core2axi/core2axi.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/core2axi_wrap.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/core_region.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/includes/debug_bus.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/components/generic_fifo.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/apb/apb_event_unit/generic_service_unit.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/apb/apb_i2c/i2c_master_bit_ctrl.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/apb/apb_i2c/i2c_master_byte_ctrl.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/instr_ram_wrap.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/periph_bus_wrap.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/peripherals.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/components/pulp_clock_inverter.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/components/pulp_clock_mux2.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/pulpino_top.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/ram_mux.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/components/rstgen.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/apb/apb_event_unit/sleep_unit.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/sp_ram_wrap.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/apb/apb_spi_master/spi_master_apb_if.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_spi_master/spi_master_clkgen.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_spi_master/spi_master_controller.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_spi_master/spi_master_fifo.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_spi_master/spi_master_rx.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_spi_master/spi_master_tx.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_spi_slave/spi_slave_axi_plug.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_spi_slave/spi_slave_cmd_parser.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_spi_slave/spi_slave_controller.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_spi_slave/spi_slave_dc_fifo.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_spi_slave/spi_slave_regs.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_spi_slave/spi_slave_rx.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_spi_slave/spi_slave_syncro.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/axi/axi_spi_slave/spi_slave_tx.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/apb/apb_timer/timer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/zero-riscy/include/zeroriscy_defines.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/zero-riscy/include/zeroriscy_config.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "$origin_dir/submodules/zero-riscy/zeroriscy_alu.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/zero-riscy/zeroriscy_compressed_decoder.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/zero-riscy/zeroriscy_controller.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/zero-riscy/zeroriscy_core.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/zero-riscy/zeroriscy_cs_registers.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/zero-riscy/zeroriscy_debug_unit.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/zero-riscy/zeroriscy_decoder.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/zero-riscy/zeroriscy_ex_block.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/zero-riscy/zeroriscy_fetch_fifo.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/zero-riscy/zeroriscy_id_stage.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/zero-riscy/zeroriscy_if_stage.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/zero-riscy/zeroriscy_int_controller.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/zero-riscy/zeroriscy_load_store_unit.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/zero-riscy/zeroriscy_multdiv_fast.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/zero-riscy/zeroriscy_multdiv_slow.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/zero-riscy/zeroriscy_prefetch_buffer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/zero-riscy/zeroriscy_register_file_ff.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/apb/apb_uart/apb_uart.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/submodules/apb/apb_uart/slib_clock_div.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/submodules/apb/apb_uart/slib_counter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/submodules/apb/apb_uart/slib_edge_detect.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/submodules/apb/apb_uart/slib_fifo.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/submodules/apb/apb_uart/slib_input_filter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/submodules/apb/apb_uart/slib_input_sync.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/submodules/apb/apb_uart/slib_mv_filter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/submodules/apb/apb_uart/uart_baudgen.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/submodules/apb/apb_uart/uart_interrupt.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/submodules/apb/apb_uart/uart_receiver.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/submodules/apb/apb_uart/uart_transmitter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


if {$target_board == "digilent_arty_a7_35t"} {
  set file "$origin_dir/rtl/pulpino_arty_a7.sv"
  set file [file normalize $file]
  set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
  set_property -name "file_type" -value "SystemVerilog" -objects $file_obj
}


if {$target_board == "digilent_nexys_a7_100t"} {
  set file "$origin_dir/rtl/pulpino_nexys_a7.sv"
  set file [file normalize $file]
  set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
  set_property -name "file_type" -value "SystemVerilog" -objects $file_obj
}



set file "$origin_dir/rtl/includes/apu_defines.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj




set file "$origin_dir/submodules/riscv/include/apu_core_package.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/riscv/riscv_L0_buffer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/riscv/include/riscv_defines.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/riscv/riscv_alu.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/riscv/riscv_alu_div.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/riscv/include/apu_macros.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "$origin_dir/submodules/riscv/riscv_apu_disp.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/riscv/riscv_compressed_decoder.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/riscv/riscv_controller.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/riscv/riscv_core.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/riscv/riscv_cs_registers.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/riscv/riscv_debug_unit.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/riscv/riscv_decoder.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/riscv/riscv_ex_stage.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/riscv/riscv_fetch_fifo.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/riscv/riscv_hwloop_controller.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/riscv/riscv_hwloop_regs.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/riscv/riscv_id_stage.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/riscv/riscv_if_stage.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/riscv/riscv_int_controller.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/riscv/riscv_load_store_unit.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/riscv/riscv_mult.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/riscv/riscv_prefetch_L0_buffer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/riscv/riscv_prefetch_buffer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/submodules/riscv/riscv_register_file.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj


set file "$origin_dir/rtl/kuznechik_cipher_apb_wrapper.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/kuznechik_cipher.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj


set file "$origin_dir/sw/test_sw_emb_text.dat"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Data Files" -objects $file_obj

set file "$origin_dir/sw/test_sw_emb_data.dat"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Data Files" -objects $file_obj

set file "$origin_dir/sw/boot_code.dat"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Data Files" -objects $file_obj

set file "${origin_dir}/rtl/look_up_tables/keys.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Data Files" -objects $file_obj

set file "${origin_dir}/rtl/look_up_tables/S_box.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Data Files" -objects $file_obj

set file "${origin_dir}/rtl/look_up_tables/S_box_inverted.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Data Files" -objects $file_obj

set file "${origin_dir}/rtl/look_up_tables/L_muliplications/L_16.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Data Files" -objects $file_obj

set file "${origin_dir}/rtl/look_up_tables/L_muliplications/L_32.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Data Files" -objects $file_obj

set file "${origin_dir}/rtl/look_up_tables/L_muliplications/L_133.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Data Files" -objects $file_obj

set file "${origin_dir}/rtl/look_up_tables/L_muliplications/L_148.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Data Files" -objects $file_obj

set file "${origin_dir}/rtl/look_up_tables/L_muliplications/L_192.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Data Files" -objects $file_obj

set file "${origin_dir}/rtl/look_up_tables/L_muliplications/L_194.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Data Files" -objects $file_obj

set file "${origin_dir}/rtl/look_up_tables/L_muliplications/L_251.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Data Files" -objects $file_obj



#set file "$origin_dir/rtl/xilinx_spram.v"
#set file [file normalize $file]
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property -name "file_type" -value "Verilog" -objects $file_obj


#set file "$origin_dir/submodules/riscv/riscv_alu_basic.sv"
#set file [file normalize $file]
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

#set file "$origin_dir/submodules/riscv/riscv_tracer.sv"
#set file [file normalize $file]
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
if {$target_board == "digilent_arty_a7_35t"} {
  set obj [get_filesets sources_1]
  set_property -name "top" -value "pulpino_arty_a7" -objects $obj
}

if {$target_board == "digilent_nexys_a7_100t"} {
  set obj [get_filesets sources_1]
  set_property -name "top" -value "pulpino_nexys_a7" -objects $obj
}



## Set 'sources_1' fileset object
#set obj [get_filesets sources_1]
## Import local files from the original project
#set files [list \
# [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/xilinx_mmcm/xilinx_mmcm.xci" ]\
#]
#set imported_files [import_files -fileset sources_1 $files]

## Set 'sources_1' fileset file properties for remote files
## None

## Set 'sources_1' fileset file properties for local files
#set file "xilinx_mmcm/xilinx_mmcm.xci"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
#set_property -name "registered_with_manager" -value "1" -objects $file_obj
#if { ![get_property "is_locked" $file_obj] } {
#  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
#}


## Set 'sources_1' fileset object
#set obj [get_filesets sources_1]
# Import local files from the original project
#set files [list \
# [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/xilinx_mem_8192x32/xilinx_mem_8192x32.xci" ]\
#]
#set imported_files [import_files -fileset sources_1 $files]

## Set 'sources_1' fileset file properties for remote files
## None

## Set 'sources_1' fileset file properties for local files
#set file "xilinx_mem_8192x32/xilinx_mem_8192x32.xci"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
#set_property -name "registered_with_manager" -value "1" -objects $file_obj
#if { ![get_property "is_locked" $file_obj] } {
#  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
#}


# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties

if {$target_board == "digilent_arty_a7_35t"} {

  set file "[file normalize "$origin_dir/xdc/Arty-Master.xdc"]"
  set file_added [add_files -norecurse -fileset $obj [list $file]]
  set file "$origin_dir/xdc/Arty-Master.xdc"
  set file [file normalize $file]
  set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
  set_property -name "file_type" -value "XDC" -objects $file_obj

  # Set 'constrs_1' fileset properties
  set obj [get_filesets constrs_1]
  set_property -name "target_part" -value "xc7a35ticsg324-1L" -objects $obj

}


if {$target_board == "digilent_nexys_a7_100t"} {

  set file "[file normalize "$origin_dir/xdc/Nexys-A7-100T-Master.xdc"]"
  set file_added [add_files -norecurse -fileset $obj [list $file]]
  set file "$origin_dir/xdc/Nexys-A7-100T-Master.xdc"
  set file [file normalize $file]
  set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
  set_property -name "file_type" -value "XDC" -objects $file_obj

  # Set 'constrs_1' fileset properties
  set obj [get_filesets constrs_1]
  set_property -name "target_part" -value "xc7a100tcsg324-1" -objects $obj

}



# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}



# Set 'sim_1' fileset object

if {$target_board == "digilent_arty_a7_35t"} {

  set obj [get_filesets sim_1]
  set files [list \
   [file normalize "${origin_dir}/tb/pulpino_arty_a7_tb.sv"] \
  ]
  add_files -norecurse -fileset $obj $files

  # Set 'sim_1' fileset file properties for remote files
  set file "$origin_dir/tb/pulpino_arty_a7_tb.sv"
  set file [file normalize $file]
  set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
  set_property -name "file_type" -value "SystemVerilog" -objects $file_obj


  # Set 'sim_1' fileset file properties for local files
  # None

  # Set 'sim_1' fileset properties
  set obj [get_filesets sim_1]
  set_property -name "top" -value "pulpino_arty_a7_tb" -objects $obj
  set_property -name "top_auto_set" -value "0" -objects $obj
  set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

}


if {$target_board == "digilent_nexys_a7_100t"} {

  set obj [get_filesets sim_1]
  set files [list \
   [file normalize "${origin_dir}/tb/pulpino_nexys_a7_tb.sv"] \
  ]
  add_files -norecurse -fileset $obj $files

  # Set 'sim_1' fileset file properties for remote files
  set file "$origin_dir/tb/pulpino_nexys_a7_tb.sv"
  set file [file normalize $file]
  set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
  set_property -name "file_type" -value "SystemVerilog" -objects $file_obj


  # Set 'sim_1' fileset file properties for local files
  # None

  # Set 'sim_1' fileset properties
  set obj [get_filesets sim_1]
  set_property -name "top" -value "pulpino_nexys_a7_tb" -objects $obj
  set_property -name "top_auto_set" -value "0" -objects $obj
  set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

}


source $origin_dir/ip/ips.tcl

set_property AUTO_INCREMENTAL_CHECKPOINT 1 [get_runs impl_1]
set_property AUTO_INCREMENTAL_CHECKPOINT 1 [get_runs synth_1]

puts "INFO: Project created:${_xil_proj_name_}"
